### ISSUE TITLE
bug upon start

### ISSUE THREAD

**Issue by ghost** [backupparachute/capistrano-unicorn#1]
rails s
/usr/local/rvm/gems/ruby-1.9.3-p551@global/gems/bundler-1.7.6/lib/bundler/runtime.rb:76:in `require': /usr/local/rvm/gems/ruby-1.9.3-p551/bundler/gems/capistrano-unicorn-2047ba1a2266/lib/capistrano-unicorn.rb:73: syntax error, unexpected keyword_end, expecting $end (SyntaxError)
    from /usr/local/rvm/gems/ruby-1.9.3-p551@global/gems/bundler-1.7.6/lib/bundler/runtime.rb:76:in`block (2 levels) in require'
    from /usr/local/rvm/gems/ruby-1.9.3-p551@global/gems/bundler-1.7.6/lib/bundler/runtime.rb:72:in `each'
    from /usr/local/rvm/gems/ruby-1.9.3-p551@global/gems/bundler-1.7.6/lib/bundler/runtime.rb:72:in`block in require'
    from /usr/local/rvm/gems/ruby-1.9.3-p551@global/gems/bundler-1.7.6/lib/bundler/runtime.rb:61:in `each'
    from /usr/local/rvm/gems/ruby-1.9.3-p551@global/gems/bundler-1.7.6/lib/bundler/runtime.rb:61:in`require'
    from /usr/local/rvm/gems/ruby-1.9.3-p551@global/gems/bundler-1.7.6/lib/bundler.rb:133:in `require'
    from /vagrant/metro-carrier-profile/config/application.rb:7:in`<top (required)>'
    from /usr/local/rvm/gems/ruby-1.9.3-p551/gems/railties-4.1.7/lib/rails/commands/commands_tasks.rb:79:in `require'
    from /usr/local/rvm/gems/ruby-1.9.3-p551/gems/railties-4.1.7/lib/rails/commands/commands_tasks.rb:79:in`block in server'
    from /usr/local/rvm/gems/ruby-1.9.3-p551/gems/railties-4.1.7/lib/rails/commands/commands_tasks.rb:76:in `tap'
    from /usr/local/rvm/gems/ruby-1.9.3-p551/gems/railties-4.1.7/lib/rails/commands/commands_tasks.rb:76:in`server'
    from /usr/local/rvm/gems/ruby-1.9.3-p551/gems/railties-4.1.7/lib/rails/commands/commands_tasks.rb:40:in `run_command!'
    from /usr/local/rvm/gems/ruby-1.9.3-p551/gems/railties-4.1.7/lib/rails/commands.rb:17:in`<top (required)>'
    from /vagrant/metro-carrier-profile/bin/rails:8:in `require'
    from /vagrant/metro-carrier-profile/bin/rails:8:in`<top (required)>'
    from /usr/local/rvm/gems/ruby-1.9.3-p551/gems/spring-1.2.0/lib/spring/client/rails.rb:27:in `load'
    from /usr/local/rvm/gems/ruby-1.9.3-p551/gems/spring-1.2.0/lib/spring/client/rails.rb:27:in`call'
    from /usr/local/rvm/gems/ruby-1.9.3-p551/gems/spring-1.2.0/lib/spring/client/command.rb:7:in `call'
    from /usr/local/rvm/gems/ruby-1.9.3-p551/gems/spring-1.2.0/lib/spring/client.rb:26:in`run'
    from /usr/local/rvm/gems/ruby-1.9.3-p551/gems/spring-1.2.0/bin/spring:48:in `<top (required)>'
    from /usr/local/rvm/gems/ruby-1.9.3-p551/gems/spring-1.2.0/lib/spring/binstub.rb:11:in`load'
    from /usr/local/rvm/gems/ruby-1.9.3-p551/gems/spring-1.2.0/lib/spring/binstub.rb:11:in `<top (required)>'
    from /vagrant/metro-carrier-profile/bin/spring:16:in`require'
    from /vagrant/metro-carrier-profile/bin/spring:16:in `<top (required)>'
    from bin/rails:3:in`load'
    from bin/rails:3:in `<main>'

**Comment by ghost** [comment]
GIT
  remote: git://github.com/backupparachute/capistrano-unicorn.git
  revision: 2047ba1a2266ac7f0f0ada1ab033f20f3c903f92
  specs:
    capistrano-unicorn (0.1.5)
      capistrano (< 3.0)
